name: Build Flutter App

on:
  push:
  pull_request:

jobs:
  build_flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release and Upload APK
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }-${{ github.sha }}-${{ github.run_number }}
          tag_name: ${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
