name: Build Flutter test

on:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches-ignore:
      - main
      - dev

jobs:
  build_flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test